project:
  type: website

website:
  title: "Home"
  navbar:
    right:
      - about.qmd
      - icon: linkedin
        href: https://www.linkedin.com/in/wallacedanielk/
      - icon: github
        href: https://github.com/wallacedanielk
format:
  html:
    theme: cosmo
    css: styles.css



